#!/usr/bin/env bash
# best school ten times but 4th and 8th change
for((i = 1; i <= 10; i++)); 
do 
	if ((i == 4))
	then
		echo "bad luck";
	elif ((i == 8))
	then
		echo "good luck";	
	else
		echo "Best School";
	fi
done
