#!/usr/bin/env bash
# best school twenty times but 4th 9 and 17th change
count=1
while ((count<=20)); 
do 
	case $count in
		4) echo -e "4\nbad luck from China";;
		9) echo -e "9\nbad luck from Japan";;
		17) echo -e "17\nbad luck  from Itraly";;
		*) echo "$count";;
	esac
	((count++))
done
